SEPOLICY_PATH := device/xiaomi/miatoll/sepolicy/misys
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(SEPOLICY_PATH)/private
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(SEPOLICY_PATH)/public
BOARD_VENDOR_SEPOLICY_DIRS += $(SEPOLICY_PATH)/vendor